# TokIntel v2 Configuration
# This file contains all configuration settings for TokIntel

# Basic settings
model: "gpt-4"
language: "it"

# Analysis keywords
keywords:
  - "motivazione"
  - "hook"
  - "viral"
  - "emozione"
  - "engagement"
  - "trend"

# Analysis weights
weights:
  keywords: 1.5
  speech_density: 1.0
  ocr: 1.2
  engagement: 1.0
  viral_potential: 1.3

# Output settings
export_format: ["csv", "json"]
output_folder: "output/"

# LLM configuration
llm_config:
  model: "gpt-4"
  endpoint: null  # Set to local endpoint if using local LLM
  api_key: null   # Set your OpenAI API key here
  timeout: 30
  max_retries: 3
  temperature: 0.7
  max_tokens: 500

# Processing settings
frame_extraction_interval: 30
max_video_duration: 300

# Logging settings
log_level: "INFO"
log_file: null  # Set to file path for file logging
log_rotation_enabled: true  # Enable log rotation (default: true)
log_max_bytes: 10485760     # 10 MB per file
log_backup_count: 5         # Number of rotated log files to keep

# Batch analysis settings
batch_analysis:
  max_concurrent: 3
  delay_seconds: 2
  retry_attempts: 2
  auto_analyze_on_save: false

# Trend analysis settings
trend_analysis:
  default_period_days: 30
  max_keywords: 20
  max_emotions: 10
  min_frequency: 1

# Video status management
video_status:
  auto_update_on_analysis: true
  default_status: "new"
  status_options: ["new", "analyzed", "error"]
