name: TokIntel v2 - CI & Coverage

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black flake8 isort mypy pytest pytest-cov

      - name: Run Black (code formatting)
        run: black --check --diff .

      - name: Run isort (import sorting)
        run: isort . --check --diff

      - name: Run Flake8 (linting)
        run: flake8 .

      - name: Run MyPy (type checking)
        run: mypy . --ignore-missing-imports --no-strict-optional

      - name: Run Pytest (unit/integration tests + coverage)
        run: pytest --cov=TokIntel_v2 tests/

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: false 